// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/theflyingcodr/backbone"
	"sync"
)

var (
	lockThingReaderWriterMockCreate sync.RWMutex
	lockThingReaderWriterMockDelete sync.RWMutex
	lockThingReaderWriterMockThing  sync.RWMutex
	lockThingReaderWriterMockThings sync.RWMutex
	lockThingReaderWriterMockUpdate sync.RWMutex
)

// Ensure, that ThingReaderWriterMock does implement ThingReaderWriter.
// If this is not the case, regenerate this file with moq.
var _ backbone.ThingReaderWriter = &ThingReaderWriterMock{}

// ThingReaderWriterMock is a mock implementation of ThingReaderWriter.
//
//     func TestSomethingThatUsesThingReaderWriter(t *testing.T) {
//
//         // make and configure a mocked ThingReaderWriter
//         mockedThingReaderWriter := &ThingReaderWriterMock{
//             CreateFunc: func(ctx context.Context, args backbone.ThingCreate) (*backbone.Thing, error) {
// 	               panic("mock out the Create method")
//             },
//             DeleteFunc: func(ctx context.Context, args backbone.ThingArgs) error {
// 	               panic("mock out the Delete method")
//             },
//             ThingFunc: func(ctx context.Context, args backbone.ThingArgs) (*backbone.Thing, error) {
// 	               panic("mock out the Thing method")
//             },
//             ThingsFunc: func(ctx context.Context) ([]*backbone.Thing, error) {
// 	               panic("mock out the Things method")
//             },
//             UpdateFunc: func(ctx context.Context, args backbone.ThingArgs, req backbone.ThingUpdate) (*backbone.Thing, error) {
// 	               panic("mock out the Update method")
//             },
//         }
//
//         // use mockedThingReaderWriter in code that requires ThingReaderWriter
//         // and then make assertions.
//
//     }
type ThingReaderWriterMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, args backbone.ThingCreate) (*backbone.Thing, error)

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, args backbone.ThingArgs) error

	// ThingFunc mocks the Thing method.
	ThingFunc func(ctx context.Context, args backbone.ThingArgs) (*backbone.Thing, error)

	// ThingsFunc mocks the Things method.
	ThingsFunc func(ctx context.Context) ([]*backbone.Thing, error)

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, args backbone.ThingArgs, req backbone.ThingUpdate) (*backbone.Thing, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args backbone.ThingCreate
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args backbone.ThingArgs
		}
		// Thing holds details about calls to the Thing method.
		Thing []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args backbone.ThingArgs
		}
		// Things holds details about calls to the Things method.
		Things []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Args is the args argument value.
			Args backbone.ThingArgs
			// Req is the req argument value.
			Req backbone.ThingUpdate
		}
	}
}

// Create calls CreateFunc.
func (mock *ThingReaderWriterMock) Create(ctx context.Context, args backbone.ThingCreate) (*backbone.Thing, error) {
	if mock.CreateFunc == nil {
		panic("ThingReaderWriterMock.CreateFunc: method is nil but ThingReaderWriter.Create was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args backbone.ThingCreate
	}{
		Ctx:  ctx,
		Args: args,
	}
	lockThingReaderWriterMockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	lockThingReaderWriterMockCreate.Unlock()
	return mock.CreateFunc(ctx, args)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//     len(mockedThingReaderWriter.CreateCalls())
func (mock *ThingReaderWriterMock) CreateCalls() []struct {
	Ctx  context.Context
	Args backbone.ThingCreate
} {
	var calls []struct {
		Ctx  context.Context
		Args backbone.ThingCreate
	}
	lockThingReaderWriterMockCreate.RLock()
	calls = mock.calls.Create
	lockThingReaderWriterMockCreate.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *ThingReaderWriterMock) Delete(ctx context.Context, args backbone.ThingArgs) error {
	if mock.DeleteFunc == nil {
		panic("ThingReaderWriterMock.DeleteFunc: method is nil but ThingReaderWriter.Delete was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args backbone.ThingArgs
	}{
		Ctx:  ctx,
		Args: args,
	}
	lockThingReaderWriterMockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	lockThingReaderWriterMockDelete.Unlock()
	return mock.DeleteFunc(ctx, args)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//     len(mockedThingReaderWriter.DeleteCalls())
func (mock *ThingReaderWriterMock) DeleteCalls() []struct {
	Ctx  context.Context
	Args backbone.ThingArgs
} {
	var calls []struct {
		Ctx  context.Context
		Args backbone.ThingArgs
	}
	lockThingReaderWriterMockDelete.RLock()
	calls = mock.calls.Delete
	lockThingReaderWriterMockDelete.RUnlock()
	return calls
}

// Thing calls ThingFunc.
func (mock *ThingReaderWriterMock) Thing(ctx context.Context, args backbone.ThingArgs) (*backbone.Thing, error) {
	if mock.ThingFunc == nil {
		panic("ThingReaderWriterMock.ThingFunc: method is nil but ThingReaderWriter.Thing was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args backbone.ThingArgs
	}{
		Ctx:  ctx,
		Args: args,
	}
	lockThingReaderWriterMockThing.Lock()
	mock.calls.Thing = append(mock.calls.Thing, callInfo)
	lockThingReaderWriterMockThing.Unlock()
	return mock.ThingFunc(ctx, args)
}

// ThingCalls gets all the calls that were made to Thing.
// Check the length with:
//     len(mockedThingReaderWriter.ThingCalls())
func (mock *ThingReaderWriterMock) ThingCalls() []struct {
	Ctx  context.Context
	Args backbone.ThingArgs
} {
	var calls []struct {
		Ctx  context.Context
		Args backbone.ThingArgs
	}
	lockThingReaderWriterMockThing.RLock()
	calls = mock.calls.Thing
	lockThingReaderWriterMockThing.RUnlock()
	return calls
}

// Things calls ThingsFunc.
func (mock *ThingReaderWriterMock) Things(ctx context.Context) ([]*backbone.Thing, error) {
	if mock.ThingsFunc == nil {
		panic("ThingReaderWriterMock.ThingsFunc: method is nil but ThingReaderWriter.Things was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	lockThingReaderWriterMockThings.Lock()
	mock.calls.Things = append(mock.calls.Things, callInfo)
	lockThingReaderWriterMockThings.Unlock()
	return mock.ThingsFunc(ctx)
}

// ThingsCalls gets all the calls that were made to Things.
// Check the length with:
//     len(mockedThingReaderWriter.ThingsCalls())
func (mock *ThingReaderWriterMock) ThingsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	lockThingReaderWriterMockThings.RLock()
	calls = mock.calls.Things
	lockThingReaderWriterMockThings.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *ThingReaderWriterMock) Update(ctx context.Context, args backbone.ThingArgs, req backbone.ThingUpdate) (*backbone.Thing, error) {
	if mock.UpdateFunc == nil {
		panic("ThingReaderWriterMock.UpdateFunc: method is nil but ThingReaderWriter.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Args backbone.ThingArgs
		Req  backbone.ThingUpdate
	}{
		Ctx:  ctx,
		Args: args,
		Req:  req,
	}
	lockThingReaderWriterMockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	lockThingReaderWriterMockUpdate.Unlock()
	return mock.UpdateFunc(ctx, args, req)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//     len(mockedThingReaderWriter.UpdateCalls())
func (mock *ThingReaderWriterMock) UpdateCalls() []struct {
	Ctx  context.Context
	Args backbone.ThingArgs
	Req  backbone.ThingUpdate
} {
	var calls []struct {
		Ctx  context.Context
		Args backbone.ThingArgs
		Req  backbone.ThingUpdate
	}
	lockThingReaderWriterMockUpdate.RLock()
	calls = mock.calls.Update
	lockThingReaderWriterMockUpdate.RUnlock()
	return calls
}
